name: DevOps CI/CD with ECR

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: us-east-1

    - name: Login to ECR
      run: |
        aws ecr get-login-password --region us-east-1 | \
        docker login --username AWS --password-stdin \
        <account-id>.dkr.ecr.us-east-1.amazonaws.com

    - name: Build Docker Image
      run: docker build -t react-devops-app .

    - name: Tag Image
      run: |
        docker tag react-devops-app:latest \
        <account-id>.dkr.ecr.us-east-1.amazonaws.com/react-devops-app:latest

    - name: Push to ECR
      run: |
        docker push <account-id>.dkr.ecr.us-east-1.amazonaws.com/react-devops-app:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          aws ecr get-login-password --region us-east-1 | \
          docker login --username AWS --password-stdin \
          <account-id>.dkr.ecr.us-east-1.amazonaws.com

          docker stop react-container || true
          docker rm react-container || true

          docker pull <account-id>.dkr.ecr.us-east-1.amazonaws.com/react-devops-app:latest

          docker run -d -p 80:3000 --name react-container \
          <account-id>.dkr.ecr.us-east-1.amazonaws.com/react-devops-app:latest